package gui;

import javax.swing.JOptionPane;
import org.antlr.v4.gui.Trees;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ParseTree;
import parser.ExpressoesLexer;
import parser.ExpressoesParser;
import visitor.ExpressoesVisitorImpl;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExpressao = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtExpressao = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnProcessar = new javax.swing.JButton();
        checkMostrarAnalise = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parser Expressões");

        lblExpressao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblExpressao.setText("Expressão:");

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblResultado.setText("Resultado:");

        txtExpressao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtExpressao.setText("6+5");

        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtResultado.setEnabled(false);

        btnProcessar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });

        checkMostrarAnalise.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        checkMostrarAnalise.setText("Mostrar Análise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado)
                            .addComponent(lblExpressao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExpressao)
                            .addComponent(txtResultado))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkMostrarAnalise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnProcessar)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpressao)
                    .addComponent(txtExpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessar)
                    .addComponent(checkMostrarAnalise))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        
        try {
            
            ExpressoesLexer lexer = new ExpressoesLexer(
                    CharStreams.fromString( txtExpressao.getText() ) );
            CommonTokenStream tokens = new CommonTokenStream( lexer );
            ExpressoesParser parser = new ExpressoesParser( tokens );
            ParseTree tree = parser.programa();

            ExpressoesVisitorImpl visitor = new ExpressoesVisitorImpl();
            visitor.visit( tree );
            txtResultado.setText( String.valueOf( visitor.valorFinal ) );
            
            if ( checkMostrarAnalise.isSelected() ) {
                mostrarDadosAnalise( null, parser, tree, true );
            }

        } catch ( RecognitionException exc ) {
            JOptionPane.showMessageDialog( this, exc.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE );
        } catch ( Exception exc ) {
            JOptionPane.showMessageDialog( this, exc.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE );
        }
        
    }//GEN-LAST:event_btnProcessarActionPerformed

    public static void mostrarDadosAnalise(
            CommonTokenStream tokens,
            Parser parser,
            ParseTree tree,
            boolean mostrarTestRig ) {

        if ( tokens != null ) {
            for ( Token t : tokens.getTokens() ) {
                System.out.println( t );
            }
        }

        if ( parser != null && tree != null ) {

            System.out.println( tree.getText() );
            System.out.println( tree.toStringTree( parser ) );

            if ( mostrarTestRig ) {
                Trees.inspect( tree, parser );
            }

        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( Janela.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( Janela.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( Janela.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( Janela.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Janela().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessar;
    private javax.swing.JCheckBox checkMostrarAnalise;
    private javax.swing.JLabel lblExpressao;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtExpressao;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
